# Generated by Django 4.1.3 on 2023-06-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetaskdocument',
            old_name='process_id',
            new_name='maintenance_task_document_id',
        ),
    ]
