# Generated by Django 4.1.3 on 2023-08-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedevice',
            name='parent_maintenance_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_maintenance_device_ids', to='maintenance.maintenancedevice'),
        ),
    ]
