# Generated by Django 4.1.3 on 2023-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_process_id_maintenancetaskdocument_maintenance_task_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
