# Generated by Django 4.1.3 on 2023-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancedevice_parent_maintenance_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedevice',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
    ]
