# Generated by Django 4.1.3 on 2023-06-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancetask_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetaskdocument',
            name='maintenance_task_document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_task_document_ids', to='maintenance.maintenancetask'),
        ),
    ]
