# Generated by Django 4.1.3 on 2023-08-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancedevice_is_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='is_part',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='parent_maintenance_detail',
        ),
    ]
