# Generated by Django 4.1.3 on 2023-08-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_remove_maintenancedevice_is_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedevice',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancedevice',
            name='parent_maintenance_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_maintenance_device_ids', to='maintenance.maintenancedevice'),
        ),
    ]
