# Generated by Django 4.1.3 on 2023-08-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancedevice_is_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='is_part',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='parent_maintenance_detail',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='section',
        ),
        migrations.AddField(
            model_name='device',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaintenanceDeviceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_device_item_ids', to='maintenance.device')),
                ('maintenance_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_device_item_ids', to='maintenance.maintenancedevice')),
                ('members', models.ManyToManyField(blank=True, related_name='maintenance_device_item_user_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starting_date',),
            },
        ),
    ]
