# Generated by Django 4.1.3 on 2023-08-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenancetask_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetaskdocument',
            old_name='maintenance_task_document',
            new_name='maintenance_task',
        ),
    ]
