# Generated by Django 4.1.3 on 2023-06-05 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ending_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='starting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
