# Generated by Django 4.1.3 on 2023-06-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_device_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='ending_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='starting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
