# Generated by Django 4.1.3 on 2023-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_alter_devicedocument_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedocument',
            name='path',
            field=models.FileField(null=True, upload_to='documents/path/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='maintenancetaskdocument',
            name='path',
            field=models.FileField(null=True, upload_to='documents/path/%Y/%m'),
        ),
    ]
