# Generated by Django 4.1.3 on 2023-06-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_alter_devicedocument_path_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancetask',
            unique_together={('name', 'maintenance_device')},
        ),
    ]
