# Generated by Django 4.1.3 on 2023-07-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_alter_maintenancetask_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedocument',
            old_name='process',
            new_name='device',
        ),
    ]
